version: '3.8'
services:
  recordViscera:
    build: .
    environment:
      TZ: Asia/Tokyo
    image: node:18
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - .:/project
    working_dir: /project
    restart: always
    # command: npm start